export type SplitMember = {
  id: string;
  name: string;
  percent: number;
};

export type ContractInput = {
  studioName: string;
  period: string;
  totalRevenue: number;
  members: SplitMember[];
};

export function generateSplitContract(input: ContractInput): string {
  const { studioName, period, totalRevenue, members } = input;
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const totalPercent = members.reduce((sum, m) => sum + m.percent, 0);

  const memberLines = members
    .map((m) => {
      const amount = (totalRevenue * m.percent) / 100;
      return `  • ${m.name}: ${m.percent}% — $${amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    })
    .join("\n");

  return `REVENUE SPLIT AGREEMENT
═══════════════════════════════════════════════════════════════

This Revenue Split Agreement ("Agreement") is entered into as of ${date}
by and between the parties listed below, collectively operating as
"${studioName}" ("Studio").

PERIOD COVERED: ${period}
GROSS REVENUE: $${totalRevenue.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}

───────────────────────────────────────────────────────────────
1. PURPOSE
───────────────────────────────────────────────────────────────
The parties wish to formalize the distribution of revenue generated
during the period stated above from content creation, sponsorships,
platform payouts, merchandise, and related creator income.

───────────────────────────────────────────────────────────────
2. REVENUE ALLOCATION
───────────────────────────────────────────────────────────────
Total allocated: ${totalPercent}%

${memberLines}

Any remaining balance after operational expenses shall be distributed
according to the percentages above within 15 business days of receipt.

───────────────────────────────────────────────────────────────
3. EXPENSES
───────────────────────────────────────────────────────────────
Approved business expenses (software, equipment, contractors, ads)
may be deducted from gross revenue prior to split calculation,
provided they are documented and pre-approved by a majority of
active members.

───────────────────────────────────────────────────────────────
4. PAYMENT TERMS
───────────────────────────────────────────────────────────────
Payments shall be made via agreed payment method (PayPal, bank transfer,
or platform-native payout) within 15 business days of revenue receipt.
Late payments accrue 1.5% monthly interest.

───────────────────────────────────────────────────────────────
5. INTELLECTUAL PROPERTY
───────────────────────────────────────────────────────────────
Content created during this period remains jointly owned by all
parties proportional to their revenue share, unless otherwise
specified in a separate IP assignment agreement.

───────────────────────────────────────────────────────────────
6. TERMINATION
───────────────────────────────────────────────────────────────
Either party may terminate with 30 days written notice. Revenue
earned prior to termination date shall still be distributed per
this Agreement.

───────────────────────────────────────────────────────────────
7. GOVERNING LAW
───────────────────────────────────────────────────────────────
This Agreement shall be governed by the laws of the jurisdiction
in which the Studio is registered.

───────────────────────────────────────────────────────────────
SIGNATURES
───────────────────────────────────────────────────────────────

${members.map((m) => `${m.name} (${m.percent}%)\nSignature: _________________________  Date: __________`).join("\n\n")}

Generated by Forge Studio — ${date}
`;
}